'use client'

import { Transaction } from "@/types"
import { formatCurrency } from "@/lib/utils"
import { useCurrency } from "@/components/Providers"
import { format } from "date-fns"
import jsPDF from "jspdf"
import { ArrowLeft, Download, FileText, FileSpreadsheet } from "lucide-react"
import Link from "next/link"

export default function TransactionDetail({ transaction }: { transaction: Transaction }) {
  const { currency } = useCurrency()

  const downloadPDF = () => {
    const doc = new jsPDF()
    
    // Header
    doc.setFontSize(22)
    doc.text("Admanics Finance", 20, 20)
    
    doc.setFontSize(14)
    doc.setTextColor(100)
    doc.text("Transaction Receipt", 20, 30)
    
    // Line
    doc.setLineWidth(0.5)
    doc.line(20, 35, 190, 35)
    
    // Details
    doc.setFontSize(12)
    doc.setTextColor(0)
    
    const startY = 50
    const lineHeight = 10
    
    doc.text(`Transaction ID: ${transaction._id}`, 20, startY)
    doc.text(`Date: ${format(new Date(transaction.date), 'MMMM dd, yyyy')}`, 20, startY + lineHeight)
    doc.text(`Title: ${transaction.title}`, 20, startY + lineHeight * 2)
    doc.text(`Category: ${transaction.category}`, 20, startY + lineHeight * 3)
    doc.text(`Type: ${transaction.type.toUpperCase()}`, 20, startY + lineHeight * 4)
    
    // Amount
    doc.setFontSize(16)
    doc.text(`Amount: ${formatCurrency(transaction.amount, currency)}`, 20, startY + lineHeight * 6)
    
    // Footer
    doc.setFontSize(10)
    doc.setTextColor(150)
    doc.text("Generated by Admanics Finance System", 20, 280)
    
    doc.save(`transaction-${transaction._id}.pdf`)
  }

  const downloadCSV = () => {
    const headers = ["ID", "Date", "Title", "Category", "Type", "Amount", "Currency"]
    const row = [
      transaction._id,
      format(new Date(transaction.date), 'yyyy-MM-dd'),
      `"${transaction.title.replace(/"/g, '""')}"`, // Escape quotes
      transaction.category,
      transaction.type,
      transaction.amount,
      currency
    ]
    
    const csvContent = "data:text/csv;charset=utf-8," 
      + headers.join(",") + "\n" 
      + row.join(",")
      
    const encodedUri = encodeURI(csvContent)
    const link = document.createElement("a")
    link.setAttribute("href", encodedUri)
    link.setAttribute("download", `transaction-${transaction._id}.csv`)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div className="min-h-screen bg-neutral-950 text-white p-6 md:p-12 font-sans">
      <div className="max-w-3xl mx-auto space-y-8">
        <Link href="/" className="inline-flex items-center text-neutral-400 hover:text-white transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Dashboard
        </Link>

        <div className="bg-neutral-900 rounded-2xl border border-neutral-800 overflow-hidden shadow-2xl">
          <div className="p-8 md:p-12 space-y-8">
            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-neutral-800 pb-8">
              <div>
                <span className={`inline-block px-3 py-1 rounded-full text-xs font-medium uppercase tracking-wider mb-3 ${
                  transaction.type === 'income' 
                    ? 'bg-green-500/10 text-green-400 border border-green-500/20' 
                    : 'bg-red-500/10 text-red-400 border border-red-500/20'
                }`}>
                  {transaction.type}
                </span>
                <h1 className="text-3xl md:text-4xl font-bold text-white">{transaction.title}</h1>
                <p className="text-neutral-400 mt-2">{format(new Date(transaction.date), 'EEEE, MMMM do, yyyy')}</p>
              </div>
              <div className="text-right">
                <p className="text-sm text-neutral-400 mb-1">Amount</p>
                <div className={`text-4xl md:text-5xl font-bold ${
                   transaction.type === 'income' ? 'text-green-500' : 'text-red-500'
                }`}>
                  {transaction.type === 'income' ? '+' : '-'}{formatCurrency(transaction.amount, currency)}
                </div>
              </div>
            </div>

            {/* Details Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <p className="text-sm font-medium text-neutral-500 uppercase tracking-wider mb-2">Category</p>
                <div className="flex items-center text-lg text-white">
                  <span className="w-2 h-2 rounded-full bg-blue-500 mr-2"></span>
                  {transaction.category}
                </div>
              </div>
              <div>
                <p className="text-sm font-medium text-neutral-500 uppercase tracking-wider mb-2">Transaction ID</p>
                <div className="text-lg text-white font-mono text-sm break-all">
                  {transaction._id}
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="pt-8 border-t border-neutral-800 flex flex-col sm:flex-row gap-4">
              <button 
                onClick={downloadPDF}
                className="flex-1 bg-white text-black hover:bg-neutral-200 font-semibold py-3 px-6 rounded-xl transition-colors flex items-center justify-center gap-2"
              >
                <FileText className="w-5 h-5" />
                Download PDF Receipt
              </button>
              <button 
                onClick={downloadCSV}
                className="flex-1 bg-neutral-800 text-white hover:bg-neutral-700 font-semibold py-3 px-6 rounded-xl transition-colors flex items-center justify-center gap-2"
              >
                <FileSpreadsheet className="w-5 h-5" />
                Download CSV
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
