'use client'

import { Transaction } from "@/types"
import { formatCurrency } from "@/lib/utils"
import { useCurrency } from "@/components/Providers"
import { format } from "date-fns"
import jsPDF from "jspdf"
import { ArrowLeft, Download, FileText, FileSpreadsheet, Pencil, Trash2, X } from "lucide-react"
import Link from "next/link"
import { deleteTransaction } from "@/app/actions"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { EntryForm } from "@/components/EntryForm"
import { ConfirmationModal } from "@/components/ConfirmationModal"
import toast from "react-hot-toast"

export default function TransactionDetail({ transaction }: { transaction: Transaction }) {
  const { currency, exchangeRate } = useCurrency()
  const router = useRouter()
  const [isDeleting, setIsDeleting] = useState(false)
  const [isEditing, setIsEditing] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)

  const handleDelete = async () => {
    setIsDeleting(true)
    const result = await deleteTransaction(transaction._id)
    setIsDeleting(false)
    setShowDeleteModal(false)
    
    if (result.success) {
      toast.success("Transaction deleted successfully")
      router.push('/')
      router.refresh()
    } else {
      toast.error(result.error || "Failed to delete transaction")
    }
  }

  const downloadPDF = () => {
    const doc = new jsPDF()
    
    // Header
    doc.setFontSize(22)
    doc.text("Admanics Finance", 20, 20)
    
    doc.setFontSize(14)
    doc.setTextColor(100)
    doc.text("Transaction Receipt", 20, 30)
    
    // Line
    doc.setLineWidth(0.5)
    doc.line(20, 35, 190, 35)
    
    // Details
    doc.setFontSize(12)
    doc.setTextColor(0)
    
    const startY = 50
    const lineHeight = 10
    
    doc.text(`Transaction ID: ${transaction._id}`, 20, startY)
    doc.text(`Date: ${format(new Date(transaction.date), 'MMMM dd, yyyy')}`, 20, startY + lineHeight)
    doc.text(`Title: ${transaction.title}`, 20, startY + lineHeight * 2)
    doc.text(`Category: ${transaction.category}`, 20, startY + lineHeight * 3)
    doc.text(`Type: ${transaction.type.toUpperCase()}`, 20, startY + lineHeight * 4)
    
    // Amount
    doc.setFontSize(16)
    doc.text(`Amount: ${formatCurrency(transaction.amount, currency, exchangeRate)}`, 20, startY + lineHeight * 6)
    
    // Footer
    doc.setFontSize(10)
    doc.setTextColor(150)
    doc.text("Generated by Admanics Finance System", 20, 280)
    
    doc.save(`transaction-${transaction._id}.pdf`)
  }

  const downloadCSV = () => {
    const headers = ["ID", "Date", "Title", "Category", "Type", "Amount", "Currency"]
    const row = [
      transaction._id,
      format(new Date(transaction.date), 'yyyy-MM-dd'),
      `"${transaction.title.replace(/"/g, '""')}"`, // Escape quotes
      transaction.category,
      transaction.type,
      transaction.amount,
      currency
    ]
    
    const csvContent = "data:text/csv;charset=utf-8," 
      + headers.join(",") + "\n" 
      + row.join(",")
      
    const encodedUri = encodeURI(csvContent)
    const link = document.createElement("a")
    link.setAttribute("href", encodedUri)
    link.setAttribute("download", `transaction-${transaction._id}.csv`)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div className="min-h-screen bg-neutral-950 text-white p-6 md:p-12 font-sans relative">
      {/* Edit Modal */}
      {isEditing && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
          <div className="max-w-xl w-full relative">
            <button 
                onClick={() => setIsEditing(false)}
                className="absolute -top-12 right-0 text-white/50 hover:text-white transition-colors"
            >
                <X className="w-8 h-8" />
            </button>
            <EntryForm 
                initialData={transaction} 
                onSuccess={() => {
                    setIsEditing(false)
                    router.refresh()
                }} 
            />
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      <ConfirmationModal
        isOpen={showDeleteModal}
        onClose={() => setShowDeleteModal(false)}
        onConfirm={handleDelete}
        title="Delete Transaction"
        description="Are you sure you want to permanently delete this transaction? This action cannot be undone and the data will be removed from the database."
        confirmText={isDeleting ? "Deleting..." : "Delete Permanently"}
        isDestructive
      />

      <div className="max-w-3xl mx-auto space-y-8">
        <div className="flex items-center justify-between">
            <Link href="/" className="inline-flex items-center text-neutral-400 hover:text-white transition-colors">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Dashboard
            </Link>
            
            <div className="flex items-center gap-3">
                <button
                    onClick={() => setIsEditing(true)}
                    className="flex items-center gap-2 px-4 py-2 bg-neutral-800 hover:bg-neutral-700 text-white rounded-lg transition-colors font-medium"
                >
                    <Pencil className="w-4 h-4" />
                    Edit
                </button>
                <button
                    onClick={() => setShowDeleteModal(true)}
                    disabled={isDeleting}
                    className="flex items-center gap-2 px-4 py-2 bg-red-500/10 hover:bg-red-500/20 text-red-500 border border-red-500/20 rounded-lg transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    <Trash2 className="w-4 h-4" />
                    Delete
                </button>
            </div>
        </div>

        <div className="bg-neutral-900 rounded-2xl border border-neutral-800 overflow-hidden shadow-2xl relative">
          <div className="p-8 md:p-12 space-y-8">
            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-neutral-800 pb-8">
              <div>
                <div className="flex items-center gap-2 mb-3">
                    <span className={`inline-block px-3 py-1 rounded-full text-xs font-medium uppercase tracking-wider ${
                    transaction.type === 'income' 
                        ? 'bg-green-500/10 text-green-400 border border-green-500/20' 
                        : 'bg-red-500/10 text-red-400 border border-red-500/20'
                    }`}>
                    {transaction.type}
                    </span>
                    {transaction.isEdited && (
                        <span className="inline-block px-3 py-1 rounded-full text-xs font-medium uppercase tracking-wider bg-yellow-500/10 text-yellow-500 border border-yellow-500/20">
                            Edited
                        </span>
                    )}
                </div>
                <h1 className="text-3xl md:text-4xl font-bold text-white max-w-lg break-words">{transaction.title}</h1>
                <p className="text-neutral-400 mt-2">{format(new Date(transaction.date), 'EEEE, MMMM do, yyyy')}</p>
                {transaction.isEdited && transaction.lastEditedAt && (
                    <p className="text-xs text-neutral-500 mt-1">
                        Last edited: {format(new Date(transaction.lastEditedAt), 'h:mm a, MMM d')}
                    </p>
                )}
              </div>
              <div className="text-right">
                <p className="text-sm text-neutral-400 mb-1">Amount</p>
                <div className={`text-4xl md:text-5xl font-bold ${
                   transaction.type === 'income' ? 'text-green-500' : 'text-red-500'
                }`}>
                  {transaction.type === 'income' ? '+' : '-'}{formatCurrency(transaction.amount, currency, exchangeRate)}
                </div>
              </div>
            </div>

            {/* Details Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <p className="text-sm font-medium text-neutral-500 uppercase tracking-wider mb-2">Category</p>
                <div className="flex items-center text-lg text-white">
                  <span className="w-2 h-2 rounded-full bg-blue-500 mr-2"></span>
                  {transaction.category}
                </div>
              </div>
              <div>
                <p className="text-sm font-medium text-neutral-500 uppercase tracking-wider mb-2">Transaction ID</p>
                <div className="text-lg text-white font-mono text-sm break-all">
                  {transaction._id}
                </div>
              </div>
            </div>

            {/* Description */}
            {transaction.description && (
                <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-6">
                    <h3 className="text-sm font-medium text-neutral-500 uppercase tracking-wider mb-3">Description</h3>
                    <p className="text-white whitespace-pre-wrap leading-relaxed">{transaction.description}</p>
                </div>
            )}

            {/* Custom Fields */}
            {transaction.customFields && transaction.customFields.length > 0 && (
                <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-6">
                    <h3 className="text-sm font-medium text-neutral-500 uppercase tracking-wider mb-4">Additional Details</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {transaction.customFields.map((field, index) => (
                            <div key={index} className="flex flex-col">
                                <span className="text-sm text-neutral-500 mb-1">{field.label}</span>
                                <span className="text-white font-medium">{field.value}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Audit Trail */}
            <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-6">
                <h3 className="text-sm font-medium text-neutral-500 uppercase tracking-wider mb-4">Activity Log</h3>
                <div className="space-y-3">
                    {transaction.createdBy && (
                        <div className="flex items-center justify-between">
                            <span className="text-sm text-neutral-400">Created by</span>
                            <span className="text-white font-medium">{transaction.createdBy.name}</span>
                        </div>
                    )}
                    {transaction.createdAt && (
                        <div className="flex items-center justify-between">
                            <span className="text-sm text-neutral-400">Created on</span>
                            <span className="text-white">{format(new Date(transaction.createdAt), 'PPpp')}</span>
                        </div>
                    )}
                    {transaction.lastEditedBy && (
                        <div className="flex items-center justify-between border-t border-neutral-800 pt-3">
                            <span className="text-sm text-neutral-400">Last edited by</span>
                            <span className="text-white font-medium">{transaction.lastEditedBy.name}</span>
                        </div>
                    )}
                    {transaction.lastEditedAt && (
                        <div className="flex items-center justify-between">
                            <span className="text-sm text-neutral-400">Last edited on</span>
                            <span className="text-white">{format(new Date(transaction.lastEditedAt), 'PPpp')}</span>
                        </div>
                    )}
                    {transaction.deletedBy && (
                        <div className="flex items-center justify-between border-t border-neutral-800 pt-3">
                            <span className="text-sm text-neutral-400">Deleted by</span>
                            <span className="text-red-400 font-medium">{transaction.deletedBy.name}</span>
                        </div>
                    )}
                    {transaction.deletedAt && (
                        <div className="flex items-center justify-between">
                            <span className="text-sm text-neutral-400">Deleted on</span>
                            <span className="text-red-400">{format(new Date(transaction.deletedAt), 'PPpp')}</span>
                        </div>
                    )}
                </div>
            </div>

            {/* Actions */}
            <div className="pt-8 border-t border-neutral-800 flex flex-col sm:flex-row gap-4">
              <button 
                onClick={downloadPDF}
                className="flex-1 bg-white text-black hover:bg-neutral-200 font-semibold py-3 px-6 rounded-xl transition-colors flex items-center justify-center gap-2"
              >
                <FileText className="w-5 h-5" />
                Download PDF Receipt
              </button>
              <button 
                onClick={downloadCSV}
                className="flex-1 bg-neutral-800 text-white hover:bg-neutral-700 font-semibold py-3 px-6 rounded-xl transition-colors flex items-center justify-center gap-2"
              >
                <FileSpreadsheet className="w-5 h-5" />
                Download CSV
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
